### ISSUE TITLE
除外キーワードを設定してない場合にすべて除外されてしまう

### ISSUE THREAD

**Issue by mapk0y** [abcang/slack-twitter-egosa#1]
新しく追加された除外キーワード（filter_stream_words_exclude）の設定がない場合に、
正規表現の記述によりすべてが除外されているようです。

**Comment by abcang** [comment]
報告ありがとうございます。
早いうちに直そうと思います。

**Comment by abcang** [comment]
@mapk0y さん

バグを修正しました。
ありがとうございました。

**Comment by abcang** [comment]
直ってない可能性が出てきたので再openします…

**Comment by abcang** [comment]
大丈夫そうでした
